#!/bin/bash

origpath=$1
sourcepath=$2
tifpath=$3

# Delete all images in the "orig" folder that were generated by Intranda PDF Importer
if [[ $origpath == *"orig_"*"_tif" ]]; then
        rm $origpath/* 2>&1
fi

# Create new high resolution uncompressed files for long term preservation
gs -dNOPAUSE -dBATCH -dQUIET -sDEVICE=tiff24nc -sCompression=none -dUseCropBox -r600x600 -dGraphicsAlphaBits=4 -dTextAlphaBits=4 -sOutputFile=$origpath/"%08d.tif" $sourcepath/*.pdf 2>&1

# Write tif-header into tif-files (use Intranda script)
/bin/bash /opt/digiverso/goobi/scripts/./iii.sh write_tiffheader $origpath

# Copy images to folder with low resolution tifs
/usr/bin/rsync -a $origpath/ $tifpath/

# Compress the images in the folder for the low resolution tifs
for file in $tifpath/*.tif
do
        # WORX - with JPEG compression:
        #convert -density 72 $file -units PixelsPerInch -compress JPEG $file 

        # WORX - with Zip compression
        # IMPORTANT:    To use ZIP compression, compile libtiff with ZIP enabled from source and install it.
        #               After installing libtiff enabled ZIP, compile ImageMagick with this libtiff again.
        #               See Wiki for instructions.
        convert -density 72 -units PixelsPerInch $file -compress Zip $file
done